services:
  postgres:
    image: scram-sha-256:postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:scram-sha-256:postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: scram-sha-256:postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: email
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - pgadmin:scram-sha-256:postgres
    ports:
      - "5050:80"

  auth-service:
    build: .
    ports:
      - "4000:4000"

volumes:
  postgres:
  pgadmin: